blank_issues_enabled: false
contact_links:
    - name: "Ask a Question"
      url: "https://github.com/spessasus/SpessaSynth/discussions/new?category=q-a"
      about: "Something is unclear? Ask a question!"
