blank_issues_enabled: false
contact_links:
    - name: "Question"
      url: "https://github.com/spessasus/SpessaSynth/discussions/new?category=q-a"
      about: "Something is unclear? Ask a question!"
    - name: "Discord Server"
      url: "https://discord.gg/TAVVxMFnsn"
      about: "Consider joining the Discord server!"
