//
// Created by spessasus on 24.05.24.
//

#ifndef SPESSASYNTH_MIDICONTROLLERS_H
#define SPESSASYNTH_MIDICONTROLLERS_H

enum MidiControllers {
    BankSelect = 0,
    ModulationWheel = 1,
    BreathController = 2,
    FootController = 4,
    PortamentoTime = 5,
    DataEntryMsb = 6,
    MainVolume = 7,
    Balance = 8,
    Pan = 10,
    ExpressionController = 11,
    EffectControl1 = 12,
    EffectControl2 = 13,
    GeneralPurposeController1 = 16,
    GeneralPurposeController2 = 17,
    GeneralPurposeController3 = 18,
    GeneralPurposeController4 = 19,
    LsbForControl0BankSelect = 32,
    LsbForControl1ModulationWheel = 33,
    LsbForControl2BreathController = 34,
    LsbForControl4FootController = 36,
    LsbForControl5PortamentoTime = 37,
    LsbForControl6DataEntry = 38,
    LsbForControl7MainVolume = 39,
    LsbForControl8Balance = 40,
    LsbForControl10Pan = 42,
    LsbForControl11ExpressionController = 43,
    LsbForControl12EffectControl1 = 44,
    LsbForControl13EffectControl2 = 45,
    SustainPedal = 64,
    PortamentoOnOff = 65,
    SostenutoPedal = 66,
    SoftPedal = 67,
    LegatoFootswitch = 68,
    Hold2Pedal = 69,
    SoundVariation = 70,
    TimbreHarmonicContent = 71,
    ReleaseTime = 72,
    AttackTime = 73,
    Brightness = 74,
    SoundController6 = 75,
    SoundController7 = 76,
    SoundController8 = 77,
    SoundController9 = 78,
    SoundController10 = 79,
    GeneralPurposeController5 = 80,
    GeneralPurposeController6 = 81,
    GeneralPurposeController7 = 82,
    GeneralPurposeController8 = 83,
    PortamentoControl = 84,
    Effects1Depth = 91,
    Effects2Depth = 92,
    Effects3Depth = 93,
    Effects4Depth = 94,
    Effects5Depth = 95,
    DataIncrement = 96,
    DataDecrement = 97,
    NRPNLsb = 98,
    NRPNMsb = 99,
    RPNLsb = 100,
    RPNMsb = 101,
    AllSoundOff = 120,
    ResetAllControllers = 121,
    LocalControlOnOff = 122,
    AllNotesOff = 123,
    OmniModeOff = 124,
    OmniModeOn = 125,
    MonoModeOn = 126,
    PolyModeOn = 127
};


#endif //SPESSASYNTH_MIDICONTROLLERS_H
